image: cirrusci/flutter:stable

stages:
  - lint
  - test
  - coverage

variables:
  FLUTTER_TEST_OUTPUTS_DIR: "test_outputs"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .pub/
    - .dart_tool/

before_script:
  - flutter pub get

lint:
  stage: lint
  script:
    - mkdir -p $FLUTTER_TEST_OUTPUTS_DIR
    - dartanalyzer lib test | tee $FLUTTER_TEST_OUTPUTS_DIR/lint.txt || echo "Linting issues found."
  artifacts:
    when: always
    paths:
      - $FLUTTER_TEST_OUTPUTS_DIR/lint.txt
    reports:
      dotenv: $FLUTTER_TEST_OUTPUTS_DIR/lint.txt

test:
  stage: test
  script:
    - flutter test --machine > $FLUTTER_TEST_OUTPUTS_DIR/test_results.json
  artifacts:
    paths:
      - $FLUTTER_TEST_OUTPUTS_DIR/test_results.json
    reports:
      junit: $FLUTTER_TEST_OUTPUTS_DIR/test_results.json

coverage:
  stage: coverage
  script:
    - flutter test --coverage
    - lcov --summary coverage/lcov.info
  artifacts:
    paths:
      - coverage/
