image: cirrusci/flutter:stable

stages:
  - test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .pub/
    - .dart_tool/

before_script:
  - flutter pub get

flutter_test:
  stage: test
  script:
    - flutter test
