stages:
  - lint
  - test

lint:
  stage: lint
  image: cirrusci/flutter:latest
  script:
    - flutter pub get
    - flutter analyze --fatal-warnings

test:
  stage: test
  image: cirrusci/flutter:latest
  before_script:
    - flutter config --no-analytics
    - flutter doctor
    - flutter pub get
  script:
    - flutter test --coverage
  artifacts:
    paths:
      - coverage/
  only:
    - main
